/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuestionSummaryResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/questions/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuestionDetailResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateSubmissionRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubmissionResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/submissions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubmissionResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateSubmissionRequest: {
            /** Format: uuid */
            questionId: string;
            language: string;
            sourceCode: string;
        };
        HealthResponse: {
            status: string;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        QuestionDetailResponse: {
            /** Format: uuid */
            id: string;
            slug: string;
            title: string;
            description: string;
            difficulty: components["schemas"]["QuestionDifficulty"];
            tags: string[];
            /** Format: int32 */
            timeLimitMs: number | string;
            /** Format: int32 */
            memoryLimitMb: number | string;
            starters: {
                [key: string]: string;
            };
            sampleTestCases: components["schemas"]["TestCaseResponse"][];
        };
        /** @enum {unknown} */
        QuestionDifficulty: "Easy" | "Medium" | "Hard";
        QuestionSummaryResponse: {
            /** Format: uuid */
            id: string;
            slug: string;
            title: string;
            difficulty: components["schemas"]["QuestionDifficulty"];
            tags: string[];
        };
        SubmissionResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            questionId: string;
            /** Format: uuid */
            userId: string;
            language: string;
            status: components["schemas"]["SubmissionStatus"];
            verdict: null | components["schemas"]["SubmissionVerdict"];
            /** Format: date-time */
            submittedAtUtc: string;
            /** Format: date-time */
            completedAtUtc?: null | string;
            compileOutput?: null | string;
            testResults?: null | components["schemas"]["SubmissionTestResultResponse"][];
        };
        /** @enum {unknown} */
        SubmissionStatus: "Pending" | "Running" | "Completed";
        SubmissionTestResultResponse: {
            /** Format: int32 */
            ordinal: number | string;
            isHidden: boolean;
            passed: boolean;
            /** Format: int64 */
            executionTimeMs: number | string;
            actualOutput: null | string;
            errorMessage: null | string;
        };
        /** @enum {unknown} */
        SubmissionVerdict: "Accepted" | "WrongAnswer" | "TimeLimitExceeded" | "MemoryLimitExceeded" | "RuntimeError" | "CompilationError" | "InternalError" | null;
        TestCaseResponse: {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            ordinal: number | string;
            input: string;
            expectedOutput: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
